CREATE TABLE FOOD(FOODITEM VARCHAR(40) PRIMARY KEY NOT NULL,
				 CALORIES INTEGER NPOT NULL,
				 PROTEIN INTEGER NOT NULL,
				 FAT INEGER NOT NULL,
				 CARBS INTEGER NOT NULL,
				 FIBER FLOAT NOT NULL);
				 